import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Nav } from '@/ui/nav/Nav';
import { Container } from '@/ui/Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className="py-8 bg-neutral-800">
          <Container>
            <Nav />
          </Container>
        </header>
        <main className='container mx-auto mt-16'>
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
